#ifndef GLSL_CONFIG_H
#define GLSL_CONFIG_H

// configuration file for vertex shaders
#ifdef VERTEX_SHADER
// attribute locations
#define VERT_A_POSITION_LOC 0
#define VERT_A_NORMAL_LOC 1
#define VERT_A_TEXTCOORD0_LOC 2
// uniform locations
#define VERT_U_PROJECTION_LOC 0
#define VERT_U_TRANSFORMATION_LOC 1
#define VERT_U_VIEW_LOC 2
#endif

/**
 * Common
 *
 * 0 - texCoord, 1 - worldPos, 3 - normal, 4 - camPos
 */
#if defined(VERTEX_SHADER) || defined(FRAGMENT_SHADER)
#define VERT_INTERFACE_BLOCK_LOC 0
#endif

#ifdef FRAGMENT_SHADER
#define COLOR_ATTACHMENT0 0
#define FRAG_U_MATERIAL_ALBEDO_LOC 10
#define FRAG_U_MATERIAL_METALLIC_LOC 11
#define FRAG_U_MATERIAL_ROUGHNESS_LOC 12
#define FRAG_U_MATERIAL_AO_LOC 13

#define MAX_POINT_LIGHTS 4
#define FRAG_U_MATERIAL_POINT_LIGHT0_POS 14
#define FRAG_U_MATERIAL_POINT_LIGHT0_COL 15
#define FRAG_U_MATERIAL_POINT_LIGHT0_RAD 16
#define FRAG_U_MATERIAL_POINT_LIGHT1_POS 17
#define FRAG_U_MATERIAL_POINT_LIGHT1_COL 18
#define FRAG_U_MATERIAL_POINT_LIGHT1_RAD 19
#define FRAG_U_MATERIAL_POINT_LIGHT2_POS 20
#define FRAG_U_MATERIAL_POINT_LIGHT2_COL 21
#define FRAG_U_MATERIAL_POINT_LIGHT2_RAD 22
#define FRAG_U_MATERIAL_POINT_LIGHT3_POS 23
#define FRAG_U_MATERIAL_POINT_LIGHT3_COL 24
#define FRAG_U_MATERIAL_POINT_LIGHT3_RAD 25
#endif

#endif
